repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict # Check for files that contain merge conflict
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
