name: cd

on:
  push:
    tags:
    - '**'

jobs:
  pypi:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@feat/build_multiple_wheels
    with:
      testpypi: true
    secrets: inherit
